"""The infinite-pool contract (pool-index) and the shape of one pooled puzzle.

The Infinite Mode plays a PRE-GENERATED pool: there is no runtime generator
(Holy Law #1), so every puzzle the endless stream can ever deal is baked into
the bundle at build time under ``frontend/public/pool/<gameId>/``. Two shapes
live here because the pool is read in two steps, and the split is what keeps the
Mode lazy:

- ``PoolIndex`` is the small manifest the Mode fetches ONCE to start a stream -
  which items exist and what band each belongs to, and nothing else. It is
  deliberately the thinnest thing that can answer "what may I play next": a
  manifest carrying words, meanings or payloads would be the whole pool in one
  request, which is exactly what the per-item files exist to avoid.
- ``PoolItem`` is ONE committed puzzle file, fetched only when the stream
  reaches it.

``PoolItem`` is NOT a ``SchemaModel``, and that is a byte decision rather than a
style one. ``SchemaModel`` stamps every document with ``version`` +
``changelog``, which is right for a document and wrong for a row: measured over
the six registered Games the stamp is 512 to 1,196 bytes while the payload it
would introduce is 291 to 1,698, so stamping a pool of ~1,800 items would spend
roughly two fifths of the whole pool on the same paragraph copied 1,800 times.
It therefore reaches ``schemas/pool-index.schema.json`` through
``PoolIndex.itemSchema`` instead - the same bridge ``Lexicon.rowSchema`` uses for
the lexicon's NDJSON rows, and for the same reason.

``payload`` is an OPEN object on the same terms as ``puzzle-file``'s: every Game
validates its own slice against its own schema at BAKE time, so Games evolve
independently and this contract never becomes a mega-schema.
"""

from __future__ import annotations

from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from yen_tamizh_backend.contracts.base import SchemaModel
from yen_tamizh_backend.contracts.common import DifficultyId, GameId, PackId

# A pool item's id, which is also the stem of its file: a zero-padded ordinal.
# Fixed width so ASCII filename order is numeric order, and so a directory
# listing reads like the index. Five digits bounds one Game's pool at 100,000
# items, which is four orders of magnitude past anything the byte budget allows.
_POOL_ID = r"^\d{5}$"


class PoolEntry(BaseModel):
    """One line of the index: which item, and which band it belongs to.

    Two fields, and the shortness is the point. The index is fetched before the
    first puzzle of a stream, so every field added to it is paid for by every
    player on every visit and multiplied by the size of the pool - a Tamil word
    on each line would roughly double it and tell the Mode nothing it uses,
    because the Mode picks by band and by what the save says it has seen.
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(pattern=_POOL_ID)
    difficulty: DifficultyId


class PoolItem(BaseModel):
    """One committed pool puzzle: its address, its framing, and its board."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(pattern=_POOL_ID)
    gameId: GameId
    packId: PackId
    difficulty: DifficultyId
    payload: dict[str, Any]


class PoolIndex(SchemaModel):
    """The manifest of one Game's pool: every item it holds, in id order.

    ``totalCount`` is redundant with ``len(items)`` by construction, and the
    validator below is what makes that redundancy safe rather than a second
    authority: a reader may show "1 of 300" without walking the list, and a
    hand-edited count is refused instead of believed.
    """

    gameId: GameId
    totalCount: int = Field(ge=0)
    items: list[PoolEntry]
    # The bridge that lands PoolItem in this schema's $defs so the frontend can
    # compile a validator for a pool FILE from the same generated bytes. Always
    # absent from a written index (the writer dumps with exclude_none), so it
    # costs the player nothing.
    itemSchema: PoolItem | None = None

    @model_validator(mode="after")
    def _the_index_counts_and_orders_what_it_lists(self) -> Self:
        if self.totalCount != len(self.items):
            raise ValueError(
                f"totalCount {self.totalCount} does not match the {len(self.items)} "
                f"items listed"
            )
        ids = [entry.id for entry in self.items]
        if len(set(ids)) != len(ids):
            raise ValueError("the index lists an id twice")
        if ids != sorted(ids):
            raise ValueError("the index is not in id order")
        return self
